### ISSUE TITLE
USER STORY Show Play oppertunities

### ISSUE THREAD

**Issue by Monika-81** [Monika-81/padel-pals#18]
As a **Site User** I want to **find missing player/players or a team that are missing a player** so that **our I can play when it suits me**

### Acceptance Criteria
- Acceptance Criteria 1: See a list of events
- Acceptance Criteria 2: See a separate event
- Acceptance Criteria 3: Comment on event

### Tasks
- [x] View to show separate event
- [x] view code to comment on event
- [x] code to delete/edit my comment
