### ISSUE TITLE
USER STORY Site Management

### ISSUE THREAD

**Issue by Monika-81** [Monika-81/padel-pals#2]
As a **Site Admin** I can **manage the site** so that **community rules are uphold**

### Acceptance Criteria
- Acceptance Criteria 1: Authenticated as a Superuser
- Acceptance Criteria 2: Moderate Comments and posts
- Acceptance Criteria 3: Admin can add posts

### Tasks
- [x] Create superuser profile
- [x] Add post- & topic model to admin panel
- [x] Add summernote editor
