### ISSUE TITLE
USER STORY Site pagination

### ISSUE THREAD

**Issue by Monika-81** [Monika-81/padel-pals#20]
As a **Site User** I can **view a paginated list of posts and/or articles** so that **I can easily select what I want to view**

### Acceptance Criteria
- Acceptance Criteria 1: Topic site pagination

### Tasks
- [x] add basic pagination code to topic html
- [x] complete pagination code to topic html
- [x] complete pagination code in all relevant templates
