### ISSUE TITLE
USER STORY Messages

### ISSUE THREAD

**Issue by Monika-81** [Monika-81/padel-pals#41]
As a **Site User** I get **confirmation messages** so that **I know everything is working correctly**

### Acceptance Criteria
- Acceptance Criteria 1: Show messages for actions
- Acceptance Criteria 2: Extra important when wrong input in form

### Tasks
- [x] Import messages from library
- [x] add code in views
- [x] add message code in templates
