### ISSUE TITLE
USER STORY Site Navigation

### ISSUE THREAD

**Issue by Monika-81** [Monika-81/padel-pals#8]
As a **Site User** I can **easily navigate the site** so that **I can find what I am looking for**

### Acceptance Criteria
- Acceptance Criteria 1: Easy navigation from navbar 
- Acceptance Criteria 2:  Easy topic navigation from via separate menu under jumbotron
- Links working

### Tasks
- [x] Clean up navbar
- [x] Link to homepage in jumbotron
- [x] add topics to every page
